import fs from 'fs';

const rawData1 = [
  { "id": 2001, "type": "browser_copy_url", "question": "（ブラウザ）現在見ている障害調査記事のURLを、チームチャットへ共有したいです。マウスを使わず、アドレスバーを選択してからURLをコピーしてください。", "expectedKeySequence": [["control", "l"], ["control", "c"]], "answer": "CORRECT", "explanation": "Ctrl+Lでアドレスバー全体を選択し、Ctrl+CでURLをコピーできます。長いURLをマウスでドラッグする必要がなく、調査結果の共有が一瞬で終わります。" },
  { "id": 2002, "type": "browser_duplicate_current_tab", "question": "（ブラウザ）今開いている管理画面を残したまま、同じページを別タブでも開いて比較したいです。現在のURLを新しいタブで開いてください。", "expectedKeySequence": [["control", "l"], ["alt", "enter"]], "answer": "CORRECT", "explanation": "Ctrl+Lで現在のURLを選択し、Alt+Enterを押すと、そのURLを新しいタブで開けます。同じ画面を複製して比較・確認したい時に便利な連続技です。" },
  { "id": 2003, "type": "browser_hard_reload", "question": "（ブラウザ）修正済みのCSSが反映されているはずなのに、自分の画面だけ古いデザインのままです。キャッシュを無視して強制再読み込みしてください。", "expectedKeyCombo": ["control", "shift", "r"], "answer": "CORRECT", "explanation": "Ctrl+Shift+Rは、キャッシュを無視してページを再読み込みするショートカットです。Web制作や検証作業で、古いCSSや画像が残っている時の確認に役立ちます。" },
  { "id": 2004, "type": "chrome_devtools_console", "question": "（Chrome）画面上の処理が失敗しています。JavaScriptエラーをすぐ確認するため、開発者ツールのConsoleを開いてください。", "expectedKeyCombo": ["control", "shift", "j"], "answer": "CORRECT", "explanation": "Ctrl+Shift+JはChromeで開発者ツールのConsoleを開くショートカットです。エラー内容やログを即座に確認できるため、Webアプリの不具合調査で頻繁に使います。" },
  { "id": 2005, "type": "vscode_select_next_occurrences", "question": "（VS Code）同じ変数名が近くに3回出てきます。検索置換を開くほどではないので、同じ単語を3つ連続で選択してください。", "expectedKeySequence": [["control", "d"], ["control", "d"], ["control", "d"]], "answer": "CORRECT", "explanation": "Ctrl+Dは、現在選択中の単語と同じ次の出現箇所を追加選択するショートカットです。繰り返し押すことでマルチカーソル編集ができ、局所的な一括修正を高速に行えます。" },
  { "id": 2006, "type": "vscode_move_line_up", "question": "（VS Code）関数内の処理順が1行だけ逆になっています。現在行を上へ移動してください。", "expectedKeyCombo": ["alt", "arrowup"], "answer": "CORRECT", "explanation": "Alt+↑は、VS Codeで現在行または選択行を上へ移動するショートカットです。切り取りと貼り付けを使わず、コードの順序をすばやく入れ替えられます。" },
  { "id": 2007, "type": "vscode_duplicate_line_down", "question": "（VS Code）似た設定行をもう1行作って、値だけ後から変えたいです。現在行を下に複製してください。", "expectedKeyCombo": ["shift", "alt", "arrowdown"], "answer": "CORRECT", "explanation": "Shift+Alt+↓は、VS Codeで現在行または選択行を下に複製するショートカットです。類似コードや設定を増やす時、コピー＆ペーストよりも少ない操作で済みます。" },
  { "id": 2008, "type": "vscode_toggle_line_comment", "question": "（VS Code）デバッグ用に一時的に処理を無効化したいです。現在行をコメント化してください。", "expectedKeyCombo": ["control", "slash"], "answer": "CORRECT", "explanation": "Ctrl+/は、VS Codeで行コメントのオン・オフを切り替えるショートカットです。処理を一時停止したり、コメントを外して戻したりする作業をすばやく行えます。" },
  { "id": 2009, "type": "vscode_replace_current_file", "question": "（VS Code）現在のファイル内で古いAPI名を新しいAPI名に置換したいです。置換入力欄を開いてください。", "expectedKeyCombo": ["control", "h"], "answer": "CORRECT", "explanation": "Ctrl+Hは、VS Codeで現在のファイル内置換を開くショートカットです。単純検索ではなく、名称変更や文言差し替えをまとめて行いたい時に使います。" },
  { "id": 2010, "type": "excel_select_used_range_from_top", "question": "（Excel）巨大な売上表を集計ツールへ渡すため、表の先頭へ戻ってから入力済み範囲をまとめて選択してください。", "expectedKeySequence": [["control", "home"], ["control", "shift", "end"]], "answer": "CORRECT", "explanation": "Ctrl+Homeで表の先頭へ移動し、Ctrl+Shift+Endで使用中範囲の最後まで選択できます。何万行ある表でも、ドラッグせずに一気に選択できます。" },
  { "id": 2011, "type": "excel_toggle_filter", "question": "（Excel）一覧表から特定部署のデータだけを絞り込みたいです。表にフィルターを設定してください。", "expectedKeyCombo": ["control", "shift", "l"], "answer": "CORRECT", "explanation": "Ctrl+Shift+Lは、Excelでオートフィルターのオン・オフを切り替えるショートカットです。大量の一覧データを条件で絞り込む作業の入口になります。" },
  { "id": 2012, "type": "excel_paste_values", "question": "（Excel）数式セルをコピーしましたが、貼り付け先には計算結果の値だけを入れたいです。形式を選択して値貼り付けを実行してください。", "expectedKeySequence": [["control", "alt", "v"], ["v"], ["enter"]], "answer": "CORRECT", "explanation": "Ctrl+Alt+Vで形式を選択して貼り付けを開き、Vで値を選び、Enterで確定します。数式や書式を持ち込まず、結果だけを貼り付けたい時に非常に便利です。" },
  { "id": 2013, "type": "excel_open_filter_dropdown", "question": "（Excel）フィルター付きの見出しセルにいます。マウスで小さな三角ボタンを押さず、現在列のフィルターメニューを開いてください。", "expectedKeyCombo": ["alt", "arrowdown"], "answer": "CORRECT", "explanation": "Alt+↓は、Excelのフィルター見出しや入力候補のドロップダウンを開く時に使えます。小さなボタンをクリックする必要がなく、絞り込み条件の設定が速くなります。" },
  { "id": 2014, "type": "explorer_rename_next_file", "question": "（エクスプローラー）スクリーンショットを連番で整理しています。選択中のファイル名を変更し、続けて次のファイル名変更へ進んでください。", "expectedKeySequence": [["f2"], ["tab"]], "answer": "CORRECT", "explanation": "F2で選択中のファイル名を編集状態にし、Tabで確定しながら次のファイルの名前変更へ進めます。大量のファイルを連続リネームする時にマウス操作を大幅に減らせます。" },
  { "id": 2015, "type": "excel_copy_current_row", "question": "（Excel）現在のセルがある受注明細行を、別シートへそのまま転記したいです。行全体を選択してコピーしてください。", "expectedKeySequence": [["shift", "space"], ["control", "c"]], "answer": "CORRECT", "explanation": "Shift+Spaceでアクティブセルの行全体を選択し、Ctrl+Cでコピーできます。行番号をクリックする必要がなく、明細行単位の転記や確認が効率化します。" },
  { "id": 1001, "type": "vscode_command_palette", "question": "（VS Code）設定変更、拡張機能のコマンド、Git関連操作をメニューから探す時間が惜しいです。コマンドパレットを開いてください。", "expectedKeyCombo": ["control", "shift", "p"], "answer": "CORRECT", "explanation": "Ctrl+Shift+Pは、VS Codeのコマンドパレットを開くショートカットです。ほぼすべての機能をキーボードから検索・実行できるため、VS Codeを高速操作する中心的な入口になります。" },
  { "id": 1002, "type": "vscode_toggle_terminal", "question": "（VS Code）コードを書きながら、すぐ下のターミナルでテストコマンドを確認したいです。統合ターミナルの表示を切り替えてください。", "expectedKeyCombo": ["control", "grave"], "answer": "CORRECT", "explanation": "Ctrl+grave（バッククォート）は、VS Codeの統合ターミナル表示を切り替えるショートカットです。エディタとターミナルをマウスなしで往復でき、開発速度が大きく上がります。" },
  { "id": 1003, "type": "vscode_new_integrated_terminal", "question": "（VS Code）既存ターミナルではサーバーを起動中です。ログを止めずに別コマンドを実行するため、新しい統合ターミナルを作成してください。", "expectedKeyCombo": ["control", "shift", "grave"], "answer": "CORRECT", "explanation": "Ctrl+Shift+grave（バッククォート）は、VS Codeで新しい統合ターミナルを作成するショートカットです。サーバー起動用、テスト用、Git操作用などを分けて作業できます。" },
  { "id": 1004, "type": "vscode_go_to_definition", "question": "（VS Code）レビュー中に、呼び出している関数の実装がどこにあるのか即確認したいです。定義へジャンプしてください。", "expectedKeyCombo": ["f12"], "answer": "CORRECT", "explanation": "F12は、VS Codeでシンボルの定義へ移動するショートカットです。関数やクラスの実装を探してフォルダを開いて回る必要がなく、コード読解が高速になります。" },
  { "id": 1005, "type": "vscode_peek_definition", "question": "（VS Code）現在の編集位置を離れずに、関数の中身だけチラ見して確認したいです。定義をピーク表示してください。", "expectedKeyCombo": ["alt", "f12"], "answer": "CORRECT", "explanation": "Alt+F12は、VS Codeで定義をピーク表示するショートカットです。ファイル移動せずに小さなビューで実装を確認できるため、文脈を失わずに調査できます。" },
  { "id": 1006, "type": "vscode_find_references", "question": "（VS Code）この関数を変更してよいか判断するため、プロジェクト内でどこから使われているか確認したいです。参照一覧を表示してください。", "expectedKeyCombo": ["shift", "f12"], "answer": "CORRECT", "explanation": "Shift+F12は、VS Codeで選択中のシンボルの参照箇所を表示するショートカットです。影響範囲を確認してから安全にリファクタリングできます。" },
  { "id": 1007, "type": "vscode_add_cursors_line_ends", "question": "（VS Code）選択した複数行の末尾に、同じコメントを一括で追記したいです。各行末にカーソルを追加してください。", "expectedKeyCombo": ["shift", "alt", "i"], "answer": "CORRECT", "explanation": "Shift+Alt+Iは、VS Codeで選択範囲内の各行末にカーソルを追加するショートカットです。複数行の末尾へ同じ文字を追加する作業を一撃で始められます。" },
  { "id": 1008, "type": "vscode_fold_all", "question": "（VS Code）巨大なファイルで全体構造だけを見たいです。すべてのコードブロックを折りたたんでください。", "expectedKeySequence": [["control", "k"], ["control", "0"]], "answer": "CORRECT", "explanation": "VS CodeではCtrl+Kに続けてCtrl+0を押すと、すべての領域を折りたためます。長大なファイルでも関数やクラスの見出しだけを見渡しやすくなります。" },
  { "id": 1009, "type": "vscode_unfold_all", "question": "（VS Code）折りたたまれたコードをまとめて確認したいです。すべての折りたたみを展開してください。", "expectedKeySequence": [["control", "k"], ["control", "j"]], "answer": "CORRECT", "explanation": "VS CodeではCtrl+Kに続けてCtrl+Jを押すと、折りたたまれた領域をすべて展開できます。構造確認後に全文を戻して読む時に便利です。" },
  { "id": 1010, "type": "vscode_add_line_comment_chord", "question": "（VS Code）一時的に選択中の複数行を無効化したいです。VS Codeの連続キー操作で行コメントを追加してください。", "expectedKeySequence": [["control", "k"], ["control", "c"]], "answer": "CORRECT", "explanation": "Ctrl+Kに続けてCtrl+Cを押すと、VS Codeで選択行に行コメントを追加できます。範囲選択した処理をまとめて無効化したい時に使える上級者向けの連続技です。" },
  { "id": 1011, "type": "vscode_format_selection_chord", "question": "（VS Code）ファイル全体ではなく、レビュー対象の一部コードだけインデントが崩れています。選択範囲だけをフォーマットしてください。", "expectedKeySequence": [["control", "k"], ["control", "f"]], "answer": "CORRECT", "explanation": "Ctrl+Kに続けてCtrl+Fを押すと、VS Codeで選択範囲だけをフォーマットできます。ファイル全体の差分を増やさず、必要な部分だけ整形したい時に有効です。" },
  { "id": 1012, "type": "terminal_clear_screen", "question": "（統合ターミナル）ログが大量に流れて、直近のテスト結果が見づらくなりました。ターミナル画面をクリアしてください。", "expectedKeyCombo": ["control", "l"], "answer": "CORRECT", "explanation": "Ctrl+Lは、多くのターミナルで画面をクリアするショートカットです。過去ログに埋もれず、次に実行するコマンドの結果を見やすくできます。" },
  { "id": 1013, "type": "powerpoint_duplicate_and_group", "question": "（PowerPoint）選択中の複数図形をテンプレートとして複製し、その複製をひとまとめにして動かせるようにしてください。", "expectedKeySequence": [["control", "d"], ["control", "g"]], "answer": "CORRECT", "explanation": "Ctrl+Dで選択中のオブジェクトを複製し、Ctrl+Gで選択中の複数オブジェクトをグループ化できます。図形セットを量産して配置する資料作成で強力な連続技です。" },
  { "id": 1014, "type": "powerpoint_copy_format_to_next_object", "question": "（PowerPoint）選択中の図形の見た目を、次の図形にもそろえたいです。書式をコピーし、次のオブジェクトへ移動して、書式を貼り付けてください。", "expectedKeySequence": [["control", "shift", "c"], ["tab"], ["control", "shift", "v"]], "answer": "CORRECT", "explanation": "Ctrl+Shift+Cで選択中オブジェクトの書式をコピーし、Tabで次のオブジェクトへ移動し、Ctrl+Shift+Vで書式を貼り付けます。スライド内の見た目をマウスなしで統一できます。" },
  { "id": 1015, "type": "powerpoint_new_slide_start_current", "question": "（PowerPoint）発表練習中に補足スライドを1枚追加しました。新しいスライドを作成し、そのスライドからすぐにスライドショーを開始してください。", "expectedKeySequence": [["control", "m"], ["shift", "f5"]], "answer": "CORRECT", "explanation": "Ctrl+Mで新しいスライドを追加し、Shift+F5で現在のスライドからスライドショーを開始できます。編集と確認をキーボードだけで連続実行できる、発表直前に便利な操作です。" }
];

const rawData2 = [
  { "id": 2016, "type": "browser_restore_tab_then_find", "question": "（ブラウザ）調査中に重要なリリースノートのタブを閉じてしまいました。タブを復元し、そのままページ内検索を開いて該当エラーコードを探せる状態にしてください。", "expectedKeySequence": [["control", "shift", "t"], ["control", "f"]], "answer": "CORRECT", "explanation": "Ctrl+Shift+Tで直前に閉じたタブを復元し、Ctrl+Fでページ内検索を開けます。履歴をたどって探し直すより、復元して即検索する方が圧倒的に速い連続技です。" },
  { "id": 2017, "type": "browser_open_downloads", "question": "（ブラウザ）CSVをダウンロードしたはずなのに、保存先を見失いました。ダウンロード一覧を開いて確認してください。", "expectedKeyCombo": ["control", "j"], "answer": "CORRECT", "explanation": "Ctrl+Jはブラウザのダウンロード一覧を開くショートカットです。ダウンロードしたファイルを探すためにフォルダーを開き直す前に、まず一覧から確認できます。" },
  { "id": 2018, "type": "browser_jump_first_tab", "question": "（ブラウザ）タブを大量に開いていますが、左端に固定している管理ダッシュボードへ一瞬で戻りたいです。最初のタブへ移動してください。", "expectedKeyCombo": ["control", "1"], "answer": "CORRECT", "explanation": "Ctrl+1はブラウザで左から1番目のタブへ移動するショートカットです。固定タブや常用ページを左端に置いておくと、どれだけタブが増えても即座に戻れます。" },
  { "id": 2019, "type": "browser_jump_last_tab", "question": "（ブラウザ）調査の最後に開いたチケットページが右端のタブにあります。タブを順番に送らず、最後のタブへ移動してください。", "expectedKeyCombo": ["control", "9"], "answer": "CORRECT", "explanation": "Ctrl+9はブラウザで一番右のタブへ移動するショートカットです。新しく開いたページが右端に集まる運用では、最後の作業ページへすばやく戻れます。" },
  { "id": 2020, "type": "chrome_open_devtools", "question": "（Chrome）本番反映後の画面でレイアウト崩れが起きています。DOMやCSSを確認するため、開発者ツールを開いてください。", "expectedKeyCombo": ["control", "shift", "i"], "answer": "CORRECT", "explanation": "Ctrl+Shift+IはChromeで開発者ツールを開くショートカットです。HTML構造、CSS、通信、Consoleなどを確認でき、Web画面の不具合調査に欠かせません。" },
  { "id": 2021, "type": "vscode_workspace_search", "question": "（VS Code）設定キーがどのファイルで使われているか、プロジェクト全体から探したいです。全体検索を開いてください。", "expectedKeyCombo": ["control", "shift", "f"], "answer": "CORRECT", "explanation": "Ctrl+Shift+FはVS Codeでワークスペース全体の検索を開くショートカットです。巨大なプロジェクトでも、ファイルを1つずつ開かずに対象文字列を横断検索できます。" },
  { "id": 2022, "type": "vscode_workspace_replace", "question": "（VS Code）古い環境変数名が複数ファイルに残っています。プロジェクト全体で置換できる画面を開いてください。", "expectedKeyCombo": ["control", "shift", "h"], "answer": "CORRECT", "explanation": "Ctrl+Shift+HはVS Codeでワークスペース全体の置換を開くショートカットです。複数ファイルにまたがる名称変更や文言修正を効率よく進められます。" },
  { "id": 2023, "type": "vscode_rename_symbol", "question": "（VS Code）変数名を手作業で置換すると、関係ない文字列まで変えそうで怖いです。現在のシンボルを安全にリネームする操作を開始してください。", "expectedKeyCombo": ["f2"], "answer": "CORRECT", "explanation": "F2はVS Codeでシンボルの名前変更を開始するショートカットです。単純な文字列置換ではなく、言語機能に基づいて変数や関数名を安全に変更できます。" },
  { "id": 2024, "type": "vscode_delete_line", "question": "（VS Code）デバッグ用のconsole出力が1行だけ残っています。選択やドラッグをせず、現在行を削除してください。", "expectedKeyCombo": ["control", "shift", "k"], "answer": "CORRECT", "explanation": "Ctrl+Shift+KはVS Codeで現在行を削除するショートカットです。行全体を選択してBackspaceを押す必要がなく、不要な行を一瞬で消せます。" },
  { "id": 2025, "type": "vscode_insert_line_below", "question": "（VS Code）現在行の下にログ出力を1行追加したいですが、行末まで移動するのが面倒です。現在行の下に新しい行を挿入してください。", "expectedKeyCombo": ["control", "enter"], "answer": "CORRECT", "explanation": "Ctrl+EnterはVS Codeで現在行の下に新しい行を挿入するショートカットです。カーソル位置が行の途中でも、すぐ下に空行を作って入力を始められます。" },
  { "id": 2026, "type": "vscode_apply_quick_fix", "question": "（VS Code）未使用importや型エラーに電球マークが出ています。クイックフィックスを開き、先頭候補を適用してください。", "expectedKeySequence": [["control", "period"], ["enter"]], "answer": "CORRECT", "explanation": "Ctrl+.でクイックフィックスを開き、Enterで候補を適用できます。import追加、型修正、lint修正などをマウスなしで処理できるため、レビュー前の整備が速くなります。" },
  { "id": 2027, "type": "excel_create_table_confirm", "question": "（Excel）CSVを開いたままの一覧表にフィルターや見やすい書式を付けたいです。テーブル作成を開始し、そのまま確定してください。", "expectedKeySequence": [["control", "t"], ["enter"]], "answer": "CORRECT", "explanation": "Ctrl+TでExcelのテーブル作成ダイアログを開き、Enterで確定できます。テーブル化するとフィルター、見出し、範囲管理が扱いやすくなり、一覧データの分析が楽になります。" },
  { "id": 2028, "type": "excel_next_worksheet", "question": "（Excel）月別シートが12枚並んだブックで、次月のシートを確認したいです。マウスでシートタブをクリックせず、次のシートへ移動してください。", "expectedKeyCombo": ["control", "pagedown"], "answer": "CORRECT", "explanation": "Ctrl+PageDownはExcelで次のワークシートへ移動するショートカットです。シート数が多いブックでも、下部の小さなタブをクリックせずに移動できます。" },
  { "id": 2029, "type": "excel_show_formulas", "question": "（Excel）集計結果が怪しいので、セルに表示されている数値ではなく数式そのものを一括で確認したいです。数式表示を切り替えてください。", "expectedKeyCombo": ["control", "grave"], "answer": "CORRECT", "explanation": "Ctrl+graveはExcelで数式の表示・非表示を切り替えるショートカットです。計算結果だけでは見えない参照ミスや式の違いを、表全体で確認できます。" },
  { "id": 2030, "type": "explorer_file_properties", "question": "（エクスプローラー）提出ファイルのサイズや更新日時をすぐ確認したいです。選択中ファイルのプロパティを開いてください。", "expectedKeyCombo": ["alt", "enter"], "answer": "CORRECT", "explanation": "Alt+Enterはエクスプローラーで選択中ファイルやフォルダーのプロパティを開くショートカットです。右クリックメニューを使わず、サイズ・場所・更新日時などを確認できます。" },
  { "id": 1016, "type": "vscode_terminal_clear", "question": "（VS Code）テストログが大量に流れて、次の実行結果が見づらくなりました。統合ターミナルを表示し、画面をクリアしてください。", "expectedKeySequence": [["control", "grave"], ["control", "l"]], "answer": "CORRECT", "explanation": "Ctrl+graveでVS Codeの統合ターミナルを表示し、Ctrl+Lでターミナル画面をクリアできます。ログに埋もれず、次のコマンド結果だけを見やすく確認できます。" },
  { "id": 1017, "type": "vscode_terminal_stop_process", "question": "（VS Code）開発サーバーが暴走してログを吐き続けています。統合ターミナルへ移動し、実行中プロセスを停止してください。", "expectedKeySequence": [["control", "grave"], ["control", "c"]], "answer": "CORRECT", "explanation": "Ctrl+graveで統合ターミナルを表示し、Ctrl+Cで実行中のプロセスへ中断を送れます。開発サーバーやテスト監視を止めたい時に使う定番の操作です。" },
  { "id": 1018, "type": "vscode_definition_and_back", "question": "（VS Code）レビュー中に関数の実装を確認したいですが、確認後は元の呼び出し元へすぐ戻りたいです。定義へ移動してから戻ってください。", "expectedKeySequence": [["f12"], ["alt", "arrowleft"]], "answer": "CORRECT", "explanation": "F12で定義へジャンプし、Alt+←で直前の位置へ戻れます。実装確認とレビュー位置への復帰をキーボードだけで行えるため、コードリーディングが途切れません。" },
  { "id": 1019, "type": "vscode_references_peek_close", "question": "（VS Code）この関数の利用箇所を一瞬だけ確認し、確認後すぐ編集画面へ戻りたいです。参照一覧を表示してから閉じてください。", "expectedKeySequence": [["shift", "f12"], ["escape"]], "answer": "CORRECT", "explanation": "Shift+F12で参照一覧を表示し、Escapeで閉じられます。影響範囲を軽く確認したい時に、パネル操作へ手を伸ばさず完結できます。" },
  { "id": 1020, "type": "vscode_quick_fix_apply", "question": "（VS Code）型エラーの箇所に修正候補が出ています。クイックフィックスを開き、選択中の候補を適用してください。", "expectedKeySequence": [["control", "period"], ["enter"]], "answer": "CORRECT", "explanation": "Ctrl+.でクイックフィックスを開き、Enterで候補を適用します。import補完、型修正、lint修正などを高速に処理できる、実装中の強力な連続技です。" },
  { "id": 1021, "type": "vscode_change_all_occurrences", "question": "（VS Code）現在選択しているローカル変数名がファイル内に何度も出ています。すべての出現箇所を一括編集できる状態にしてください。", "expectedKeyCombo": ["control", "f2"], "answer": "CORRECT", "explanation": "Ctrl+F2はVS Codeで現在の単語のすべての出現箇所を選択するショートカットです。ファイル内の同じ変数名をマルチカーソルでまとめて編集できます。" },
  { "id": 1022, "type": "vscode_expand_selection_twice", "question": "（VS Code）文字列の一部から、式全体、さらに周辺ブロックへと選択範囲を広げたいです。選択範囲を2段階拡張してください。", "expectedKeySequence": [["shift", "alt", "arrowright"], ["shift", "alt", "arrowright"]], "answer": "CORRECT", "explanation": "Shift+Alt+→はVS Codeで選択範囲を構文単位で拡張するショートカットです。2回押すことで、単語から式、式からより大きな範囲へ広げられます。" },
  { "id": 1023, "type": "vscode_shrink_selection", "question": "（VS Code）選択範囲を広げすぎて、不要な外側のブロックまで含めてしまいました。選択範囲を1段階縮小してください。", "expectedKeyCombo": ["shift", "alt", "arrowleft"], "answer": "CORRECT", "explanation": "Shift+Alt+←はVS Codeで選択範囲を1段階縮小するショートカットです。拡張しすぎた選択をマウスで選び直さず、構文単位で戻せます。" },
  { "id": 1024, "type": "vscode_trim_trailing_whitespace", "question": "（VS Code）レビュー前に、行末の余計な空白が大量に残っていることに気づきました。連続キー操作で行末空白を削除してください。", "expectedKeySequence": [["control", "k"], ["control", "x"]], "answer": "CORRECT", "explanation": "VS CodeではCtrl+Kに続けてCtrl+Xを押すと、行末の余計な空白を削除できます。差分ノイズを減らし、レビューしやすいコードに整えられます。" },
  { "id": 1025, "type": "vscode_markdown_preview_side", "question": "（VS Code）READMEを編集しながら、横にプレビューを出して表示崩れを確認したいです。Markdownプレビューを横に開いてください。", "expectedKeySequence": [["control", "k"], ["v"]], "answer": "CORRECT", "explanation": "Ctrl+Kに続けてVを押すと、VS CodeでMarkdownプレビューを横に開けます。編集画面とプレビューを並べられるため、READMEや手順書の確認が効率化します。" },
  { "id": 1026, "type": "vscode_open_keyboard_shortcuts", "question": "（VS Code）よく使う操作を自分好みに割り当てたいです。キーボードショートカット設定画面を開いてください。", "expectedKeySequence": [["control", "k"], ["control", "s"]], "answer": "CORRECT", "explanation": "Ctrl+Kに続けてCtrl+Sを押すと、VS Codeのキーボードショートカット設定を開けます。頻繁に使う機能を自分の手癖に合わせることで、作業速度をさらに上げられます。" },
  { "id": 1027, "type": "powerpoint_ungroup_duplicate_group", "question": "（PowerPoint）既存の図形グループを素材として使い回したいです。グループ解除、複製、再グループ化までキーボードで行ってください。", "expectedKeySequence": [["control", "shift", "g"], ["control", "d"], ["control", "g"]], "answer": "CORRECT", "explanation": "Ctrl+Shift+Gでグループ解除、Ctrl+Dで複製、Ctrl+Gでグループ化できます。図形パーツを分解・複製・再利用する資料作成を、マウス操作なしで進められます。" },
  { "id": 1028, "type": "powerpoint_slideshow_blackout", "question": "（PowerPoint）発表を開始した直後、口頭説明に集中してもらうため一時的に画面を黒くしたいです。スライドショーを開始してからブラックアウトしてください。", "expectedKeySequence": [["f5"], ["b"]], "answer": "CORRECT", "explanation": "F5でスライドショーを最初から開始し、Bキーで画面を黒くできます。説明に集中してもらいたい時や、投影内容を一時的に隠したい時に便利です。" },
  { "id": 1029, "type": "powerpoint_increase_font_twice", "question": "（PowerPoint）レビューで『タイトルが小さくて読めない』と指摘されました。選択中の文字サイズを2段階大きくしてください。", "expectedKeySequence": [["control", "shift", "period"], ["control", "shift", "period"]], "answer": "CORRECT", "explanation": "Ctrl+Shift+periodは、PowerPointなどで選択中テキストのフォントサイズを大きくするショートカットです。2回連続で押せば、細かいフォントサイズ調整をキーボードだけで行えます。" },
  { "id": 1030, "type": "excel_next_sheet_copy_used_range", "question": "（Excel）月次ブックで次月シートへ移動し、入力済み範囲を丸ごとコピーして別システムへ渡したいです。次のシートへ移動し、先頭から使用範囲全体を選択してコピーしてください。", "expectedKeySequence": [["control", "pagedown"], ["control", "home"], ["control", "shift", "end"], ["control", "c"]], "answer": "CORRECT", "explanation": "Ctrl+PageDownで次のシートへ移動し、Ctrl+Homeで先頭へ戻り、Ctrl+Shift+Endで使用中範囲全体を選択し、Ctrl+Cでコピーします。月次処理や集計転記で威力を発揮する実務向けの連続技です。" }
];

const allNew = [...rawData1, ...rawData2];
const kyu1 = allNew.filter(q => q.id >= 1000 && q.id < 2000);
const kyu2 = allNew.filter(q => q.id >= 2000 && q.id < 3000);

const poolData = JSON.parse(fs.readFileSync('scripts/practical_pool.json', 'utf8'));

poolData['practical-1kyu'] = kyu1;
poolData['practical-2kyu'] = kyu2;

fs.writeFileSync('scripts/practical_pool.json', JSON.stringify(poolData, null, 2));
console.log('Saved to practical_pool.json');
